eip155:8453:
  deployment id: MVP
  name: BASE
  env: prod
  LiquidityPoolAaveUSDC: "0x7C255279c098fdF6c3116D2BecD9978002c09f4b"
  LiquidityPoolUSDC: "0xB58Bb9643884abbbad64FA7eBc874c5481E5c032"
  SprinterUSDCLPShare: "0xfa89929b30bC3132f9907CBCe3F2f6f4AC0903b6"
  LiquidityHub: "0xa593A9bBBc65be342FF610a01e96da2EB8539FF2"
  SprinterLiquidityMining: "0x479D158959B59328E89f0fbF7DfeBb198c313C21"
  CensoredTransferFromMulticall: "0x7C472EBa1945E970a23C903FC8812D469a29B6bb"
  USDC: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
  Rebalancer: "0xA85Cf46c150db2600b1D03E437bedD5513869888"
  Repayer: "0x36364Acc7B9c67692CA215af09A41CBd10439511"

eip155:10:
  deployment id: MVP
  name: OP_MAINNET
  env: prod
  LiquidityPoolAaveUSDC: "0x7C255279c098fdF6c3116D2BecD9978002c09f4b"
  LiquidityPoolUSDC: "0xB58Bb9643884abbbad64FA7eBc874c5481E5c032"
  CensoredTransferFromMulticall: "0x7C472EBa1945E970a23C903FC8812D469a29B6bb"
  USDC: "0x0b2c639c533813f4aa9d7837caf62653d097ff85"
  Rebalancer: "0xA85Cf46c150db2600b1D03E437bedD5513869888"
  Repayer: "0x36364Acc7B9c67692CA215af09A41CBd10439511"

eip155:42161:
  deployment id: MVP
  name: ARBITRUM_ONE
  env: prod
  LiquidityPoolAaveUSDC: "0x7C255279c098fdF6c3116D2BecD9978002c09f4b"
  LiquidityPoolUSDC: "0xB58Bb9643884abbbad64FA7eBc874c5481E5c032"
  CensoredTransferFromMulticall: "0x7C472EBa1945E970a23C903FC8812D469a29B6bb"
  USDC: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
  Rebalancer: "0xA85Cf46c150db2600b1D03E437bedD5513869888"
  Repayer: "0x36364Acc7B9c67692CA215af09A41CBd10439511"

eip155:1:
  deployment id: MVP
  name: ETHEREUM
  env: prod
  LiquidityPoolUSDCStablecoin: "0x2781650E1d76b56b3BCD9836e4d16E04c86d3D07"
  LiquidityPoolAaveUSDCLongTerm: "0x5E8da448f3F7290cA355BbF7EF9F323ab8fDE422"
  CensoredTransferFromMulticall: "0x7C472EBa1945E970a23C903FC8812D469a29B6bb"
  USDC: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
  Rebalancer: "0xA85Cf46c150db2600b1D03E437bedD5513869888"
  Repayer: "0x36364Acc7B9c67692CA215af09A41CBd10439511"

eip155:137:
  deployment id: MVP
  name: POLYGON_MAINNET
  env: prod
  USDC: "0x3c499c542cef5e3811e1192ce70d8cc03d5c3359"
  Repayer: "0x36364Acc7B9c67692CA215af09A41CBd10439511"

eip155:130:
  deployment id: MVP
  name: UNICHAIN
  env: prod
  LiquidityPoolUSDCStablecoin: "0x2781650E1d76b56b3BCD9836e4d16E04c86d3D07"
  CensoredTransferFromMulticall: "0x7C472EBa1945E970a23C903FC8812D469a29B6bb"
  USDC: "0x078D782b760474a361dDA0AF3839290b0EF57AD6"
  Rebalancer: "0xA85Cf46c150db2600b1D03E437bedD5513869888"
  Repayer: "0x36364Acc7B9c67692CA215af09A41CBd10439511"
