eip155:8453:
  deployment id: MVP
  env: stage
  name: BASE
  LiquidityPoolAaveUSDC: "0x2B7899f3d553FCcf61122BdA60f5f9a9AE390683"
  LiquidityPoolUSDC: "0x578aD20ec27E11B3772F91cc6f435d782cc362EA"
  SprinterUSDCLPShare: "0xCb85b9fEFcA1316EFe0B7E1965A8922701fF502f"
  LiquidityHub: "0x6FD4142Be84134C5a6D45d454529A6C3c9573B61"
  SprinterLiquidityMining: "0xa85Aa9ac9EaC15BA8636cE4C8014135bC34B0525"
  CensoredTransferFromMulticall: "0xd0A630c391daEb244369DB0f75CBDF7dFeEaEaC3"
  USDC: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
  Rebalancer: "0x34Df9cD75fA0b4d8fF300AeDf7591f79dFdd61C9"
  Repayer: "0x697ECA1cae710FA0348e2173900e6C09b180C35b"
  RepayerSpark: "0x4c1545A73e2d586625e92482E706Eaa400613eb9"

eip155:10:
  deployment id: MVP
  env: stage
  name: OP_MAINNET
  LiquidityPoolAaveUSDC: "0x2B7899f3d553FCcf61122BdA60f5f9a9AE390683"
  LiquidityPoolUSDC: "0x578aD20ec27E11B3772F91cc6f435d782cc362EA"
  CensoredTransferFromMulticall: "0xd0A630c391daEb244369DB0f75CBDF7dFeEaEaC3"
  USDC: "0x0b2c639c533813f4aa9d7837caf62653d097ff85"
  Rebalancer: "0x34Df9cD75fA0b4d8fF300AeDf7591f79dFdd61C9"
  Repayer: "0x697ECA1cae710FA0348e2173900e6C09b180C35b"
  RepayerSpark: "0x4c1545A73e2d586625e92482E706Eaa400613eb9"

eip155:42161:
  deployment id: MVP
  env: stage
  name: ARBITRUM_ONE
  LiquidityPoolAaveUSDC: "0x2B7899f3d553FCcf61122BdA60f5f9a9AE390683"
  LiquidityPoolUSDC: "0x578aD20ec27E11B3772F91cc6f435d782cc362EA"
  LiquidityPoolAaveUSDCLongTerm: "0x4ce56b5D7e79dF121aF2eC055D096eF983F459e6"
  CensoredTransferFromMulticall: "0xd0A630c391daEb244369DB0f75CBDF7dFeEaEaC3"
  USDC: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
  Rebalancer: "0x34Df9cD75fA0b4d8fF300AeDf7591f79dFdd61C9"
  Repayer: "0x697ECA1cae710FA0348e2173900e6C09b180C35b"
  RepayerSpark: "0x4c1545A73e2d586625e92482E706Eaa400613eb9"

eip155:1:
  deployment id: MVP
  env: stage
  name: ETHEREUM
  LiquidityPoolUSDC: "0x578aD20ec27E11B3772F91cc6f435d782cc362EA"
  LiquidityPoolAaveUSDCLongTerm: "0x4ce56b5D7e79dF121aF2eC055D096eF983F459e6"
  CensoredTransferFromMulticall: "0xd0A630c391daEb244369DB0f75CBDF7dFeEaEaC3"
  USDC: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
  Rebalancer: "0x34Df9cD75fA0b4d8fF300AeDf7591f79dFdd61C9"
  Repayer: "0x697ECA1cae710FA0348e2173900e6C09b180C35b"
